### ISSUE TITLE
文章页和lovelist页面 图片缩放需要优化

### ISSUE THREAD

**Issue by Binning42** [zwying0814/Brave#1]
![IMG_1233(20210213-143703)](https://user-images.githubusercontent.com/29419816/108344268-e4995380-7217-11eb-8b27-4967e19743f3.JPG)
![IMG_1234(20210214-132852)](https://user-images.githubusercontent.com/29419816/108344276-e6631700-7217-11eb-802d-fa331ef4e376.JPG)
图片分辨率 1080x1249

**Comment by zwying0814** [comment]
最新版本已修复，请更新
